/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcMarketDataBaseField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcMarketDataBaseField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcMarketDataBaseField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcMarketDataBaseField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradingDay(String value) {
    ctpapiJNI.CThostFtdcMarketDataBaseField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpapiJNI.CThostFtdcMarketDataBaseField_TradingDay_get(swigCPtr, this);
  }

  public void setPreSettlementPrice(double value) {
    ctpapiJNI.CThostFtdcMarketDataBaseField_PreSettlementPrice_set(swigCPtr, this, value);
  }

  public double getPreSettlementPrice() {
    return ctpapiJNI.CThostFtdcMarketDataBaseField_PreSettlementPrice_get(swigCPtr, this);
  }

  public void setPreClosePrice(double value) {
    ctpapiJNI.CThostFtdcMarketDataBaseField_PreClosePrice_set(swigCPtr, this, value);
  }

  public double getPreClosePrice() {
    return ctpapiJNI.CThostFtdcMarketDataBaseField_PreClosePrice_get(swigCPtr, this);
  }

  public void setPreOpenInterest(double value) {
    ctpapiJNI.CThostFtdcMarketDataBaseField_PreOpenInterest_set(swigCPtr, this, value);
  }

  public double getPreOpenInterest() {
    return ctpapiJNI.CThostFtdcMarketDataBaseField_PreOpenInterest_get(swigCPtr, this);
  }

  public void setPreDelta(double value) {
    ctpapiJNI.CThostFtdcMarketDataBaseField_PreDelta_set(swigCPtr, this, value);
  }

  public double getPreDelta() {
    return ctpapiJNI.CThostFtdcMarketDataBaseField_PreDelta_get(swigCPtr, this);
  }

  public CThostFtdcMarketDataBaseField() {
    this(ctpapiJNI.new_CThostFtdcMarketDataBaseField(), true);
  }

}
