/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcErrStockDisposalActionField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcErrStockDisposalActionField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcErrStockDisposalActionField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcErrStockDisposalActionField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_InvestorID_get(swigCPtr, this);
  }

  public void setStockDisposalActionRef(int value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalActionRef_set(swigCPtr, this, value);
  }

  public int getStockDisposalActionRef() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalActionRef_get(swigCPtr, this);
  }

  public void setStockDisposalRef(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalRef_set(swigCPtr, this, value);
  }

  public String getStockDisposalRef() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalRef_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_RequestID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_SessionID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_ExchangeID_get(swigCPtr, this);
  }

  public void setStockDisposalSysID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalSysID_set(swigCPtr, this, value);
  }

  public String getStockDisposalSysID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_StockDisposalSysID_get(swigCPtr, this);
  }

  public void setActionFlag(char value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_ActionFlag_set(swigCPtr, this, value);
  }

  public char getActionFlag() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_ActionFlag_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_UserID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_InstrumentID_get(swigCPtr, this);
  }

  public void setErrorID(int value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_ErrorID_set(swigCPtr, this, value);
  }

  public int getErrorID() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_ErrorID_get(swigCPtr, this);
  }

  public void setErrorMsg(String value) {
    ctpapiJNI.CThostFtdcErrStockDisposalActionField_ErrorMsg_set(swigCPtr, this, value);
  }

  public String getErrorMsg() {
    return ctpapiJNI.CThostFtdcErrStockDisposalActionField_ErrorMsg_get(swigCPtr, this);
  }

  public CThostFtdcErrStockDisposalActionField() {
    this(ctpapiJNI.new_CThostFtdcErrStockDisposalActionField(), true);
  }

}
