/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcLimitAmountParamField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcLimitAmountParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcLimitAmountParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcLimitAmountParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInvestorRange(char value) {
    ctpapiJNI.CThostFtdcLimitAmountParamField_InvestorRange_set(swigCPtr, this, value);
  }

  public char getInvestorRange() {
    return ctpapiJNI.CThostFtdcLimitAmountParamField_InvestorRange_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcLimitAmountParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcLimitAmountParamField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiJNI.CThostFtdcLimitAmountParamField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiJNI.CThostFtdcLimitAmountParamField_InvestorID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcLimitAmountParamField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcLimitAmountParamField_ExchangeID_get(swigCPtr, this);
  }

  public void setLongAmount(double value) {
    ctpapiJNI.CThostFtdcLimitAmountParamField_LongAmount_set(swigCPtr, this, value);
  }

  public double getLongAmount() {
    return ctpapiJNI.CThostFtdcLimitAmountParamField_LongAmount_get(swigCPtr, this);
  }

  public CThostFtdcLimitAmountParamField() {
    this(ctpapiJNI.new_CThostFtdcLimitAmountParamField(), true);
  }

}
