/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcReqCancelAccountField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcReqCancelAccountField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcReqCancelAccountField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcReqCancelAccountField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTradeCode(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_TradeCode_set(swigCPtr, this, value);
  }

  public String getTradeCode() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_TradeCode_get(swigCPtr, this);
  }

  public void setBankID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankID_set(swigCPtr, this, value);
  }

  public String getBankID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankID_get(swigCPtr, this);
  }

  public void setBankBranchID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankBranchID_set(swigCPtr, this, value);
  }

  public String getBankBranchID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankBranchID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerID_get(swigCPtr, this);
  }

  public void setBrokerBranchID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerBranchID_set(swigCPtr, this, value);
  }

  public String getBrokerBranchID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerBranchID_get(swigCPtr, this);
  }

  public void setTradeDate(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_TradeDate_set(swigCPtr, this, value);
  }

  public String getTradeDate() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_TradeDate_get(swigCPtr, this);
  }

  public void setTradeTime(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_TradeTime_set(swigCPtr, this, value);
  }

  public String getTradeTime() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_TradeTime_get(swigCPtr, this);
  }

  public void setBankSerial(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankSerial_set(swigCPtr, this, value);
  }

  public String getBankSerial() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankSerial_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_TradingDay_get(swigCPtr, this);
  }

  public void setPlateSerial(int value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_PlateSerial_set(swigCPtr, this, value);
  }

  public int getPlateSerial() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_PlateSerial_get(swigCPtr, this);
  }

  public void setLastFragment(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_LastFragment_set(swigCPtr, this, value);
  }

  public char getLastFragment() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_LastFragment_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_SessionID_get(swigCPtr, this);
  }

  public void setCustomerName(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_CustomerName_set(swigCPtr, this, value);
  }

  public String getCustomerName() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_CustomerName_get(swigCPtr, this);
  }

  public void setIdCardType(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_IdCardType_set(swigCPtr, this, value);
  }

  public char getIdCardType() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_IdCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setGender(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Gender_set(swigCPtr, this, value);
  }

  public char getGender() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Gender_get(swigCPtr, this);
  }

  public void setCountryCode(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_CountryCode_set(swigCPtr, this, value);
  }

  public String getCountryCode() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_CountryCode_get(swigCPtr, this);
  }

  public void setCustType(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_CustType_set(swigCPtr, this, value);
  }

  public char getCustType() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_CustType_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_ZipCode_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Telephone_get(swigCPtr, this);
  }

  public void setMobilePhone(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_MobilePhone_set(swigCPtr, this, value);
  }

  public String getMobilePhone() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_MobilePhone_get(swigCPtr, this);
  }

  public void setFax(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Fax_set(swigCPtr, this, value);
  }

  public String getFax() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Fax_get(swigCPtr, this);
  }

  public void setEMail(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_EMail_set(swigCPtr, this, value);
  }

  public String getEMail() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_EMail_get(swigCPtr, this);
  }

  public void setMoneyAccountStatus(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_MoneyAccountStatus_set(swigCPtr, this, value);
  }

  public char getMoneyAccountStatus() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_MoneyAccountStatus_get(swigCPtr, this);
  }

  public void setBankAccount(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankAccount_set(swigCPtr, this, value);
  }

  public String getBankAccount() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankAccount_get(swigCPtr, this);
  }

  public void setBankPassWord(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankPassWord_set(swigCPtr, this, value);
  }

  public String getBankPassWord() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankPassWord_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_AccountID_get(swigCPtr, this);
  }

  public void setPassword(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Password_set(swigCPtr, this, value);
  }

  public String getPassword() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Password_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_InstallID_get(swigCPtr, this);
  }

  public void setVerifyCertNoFlag(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_VerifyCertNoFlag_set(swigCPtr, this, value);
  }

  public char getVerifyCertNoFlag() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_VerifyCertNoFlag_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_CurrencyID_get(swigCPtr, this);
  }

  public void setCashExchangeCode(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_CashExchangeCode_set(swigCPtr, this, value);
  }

  public char getCashExchangeCode() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_CashExchangeCode_get(swigCPtr, this);
  }

  public void setDigest(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_Digest_set(swigCPtr, this, value);
  }

  public String getDigest() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_Digest_get(swigCPtr, this);
  }

  public void setBankAccType(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankAccType_set(swigCPtr, this, value);
  }

  public char getBankAccType() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankAccType_get(swigCPtr, this);
  }

  public void setDeviceID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_DeviceID_set(swigCPtr, this, value);
  }

  public String getDeviceID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_DeviceID_get(swigCPtr, this);
  }

  public void setBankSecuAccType(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankSecuAccType_set(swigCPtr, this, value);
  }

  public char getBankSecuAccType() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankSecuAccType_get(swigCPtr, this);
  }

  public void setBrokerIDByBank(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerIDByBank_set(swigCPtr, this, value);
  }

  public String getBrokerIDByBank() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BrokerIDByBank_get(swigCPtr, this);
  }

  public void setBankSecuAcc(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankSecuAcc_set(swigCPtr, this, value);
  }

  public String getBankSecuAcc() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankSecuAcc_get(swigCPtr, this);
  }

  public void setBankPwdFlag(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_BankPwdFlag_set(swigCPtr, this, value);
  }

  public char getBankPwdFlag() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_BankPwdFlag_get(swigCPtr, this);
  }

  public void setSecuPwdFlag(char value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_SecuPwdFlag_set(swigCPtr, this, value);
  }

  public char getSecuPwdFlag() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_SecuPwdFlag_get(swigCPtr, this);
  }

  public void setOperNo(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_OperNo_set(swigCPtr, this, value);
  }

  public String getOperNo() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_OperNo_get(swigCPtr, this);
  }

  public void setTID(int value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_TID_set(swigCPtr, this, value);
  }

  public int getTID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_TID_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpapiJNI.CThostFtdcReqCancelAccountField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpapiJNI.CThostFtdcReqCancelAccountField_UserID_get(swigCPtr, this);
  }

  public CThostFtdcReqCancelAccountField() {
    this(ctpapiJNI.new_CThostFtdcReqCancelAccountField(), true);
  }

}
