/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcExchangeLockField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcExchangeLockField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExchangeLockField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcExchangeLockField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVolume(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return ctpapiJNI.CThostFtdcExchangeLockField_Volume_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_RequestID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return ctpapiJNI.CThostFtdcExchangeLockField_BusinessUnit_get(swigCPtr, this);
  }

  public void setLockType(char value) {
    ctpapiJNI.CThostFtdcExchangeLockField_LockType_set(swigCPtr, this, value);
  }

  public char getLockType() {
    return ctpapiJNI.CThostFtdcExchangeLockField_LockType_get(swigCPtr, this);
  }

  public void setLockLocalID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_LockLocalID_set(swigCPtr, this, value);
  }

  public String getLockLocalID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_LockLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_InstallID_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    ctpapiJNI.CThostFtdcExchangeLockField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return ctpapiJNI.CThostFtdcExchangeLockField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return ctpapiJNI.CThostFtdcExchangeLockField_NotifySequence_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpapiJNI.CThostFtdcExchangeLockField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_SettlementID_get(swigCPtr, this);
  }

  public void setLockSysID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_LockSysID_set(swigCPtr, this, value);
  }

  public String getLockSysID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_LockSysID_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return ctpapiJNI.CThostFtdcExchangeLockField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return ctpapiJNI.CThostFtdcExchangeLockField_InsertTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return ctpapiJNI.CThostFtdcExchangeLockField_CancelTime_get(swigCPtr, this);
  }

  public void setLockStatus(char value) {
    ctpapiJNI.CThostFtdcExchangeLockField_LockStatus_set(swigCPtr, this, value);
  }

  public char getLockStatus() {
    return ctpapiJNI.CThostFtdcExchangeLockField_LockStatus_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    ctpapiJNI.CThostFtdcExchangeLockField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpapiJNI.CThostFtdcExchangeLockField_SequenceNo_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return ctpapiJNI.CThostFtdcExchangeLockField_BranchID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return ctpapiJNI.CThostFtdcExchangeLockField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    ctpapiJNI.CThostFtdcExchangeLockField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return ctpapiJNI.CThostFtdcExchangeLockField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcExchangeLockField() {
    this(ctpapiJNI.new_CThostFtdcExchangeLockField(), true);
  }

}
