/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcQuoteField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcQuoteField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcQuoteField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcQuoteField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcQuoteField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiJNI.CThostFtdcQuoteField_InvestorID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpapiJNI.CThostFtdcQuoteField_InstrumentID_get(swigCPtr, this);
  }

  public void setQuoteRef(String value) {
    ctpapiJNI.CThostFtdcQuoteField_QuoteRef_set(swigCPtr, this, value);
  }

  public String getQuoteRef() {
    return ctpapiJNI.CThostFtdcQuoteField_QuoteRef_get(swigCPtr, this);
  }

  public void setUserID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_UserID_set(swigCPtr, this, value);
  }

  public String getUserID() {
    return ctpapiJNI.CThostFtdcQuoteField_UserID_get(swigCPtr, this);
  }

  public void setAskPrice(double value) {
    ctpapiJNI.CThostFtdcQuoteField_AskPrice_set(swigCPtr, this, value);
  }

  public double getAskPrice() {
    return ctpapiJNI.CThostFtdcQuoteField_AskPrice_get(swigCPtr, this);
  }

  public void setBidPrice(double value) {
    ctpapiJNI.CThostFtdcQuoteField_BidPrice_set(swigCPtr, this, value);
  }

  public double getBidPrice() {
    return ctpapiJNI.CThostFtdcQuoteField_BidPrice_get(swigCPtr, this);
  }

  public void setAskVolume(int value) {
    ctpapiJNI.CThostFtdcQuoteField_AskVolume_set(swigCPtr, this, value);
  }

  public int getAskVolume() {
    return ctpapiJNI.CThostFtdcQuoteField_AskVolume_get(swigCPtr, this);
  }

  public void setBidVolume(int value) {
    ctpapiJNI.CThostFtdcQuoteField_BidVolume_set(swigCPtr, this, value);
  }

  public int getBidVolume() {
    return ctpapiJNI.CThostFtdcQuoteField_BidVolume_get(swigCPtr, this);
  }

  public void setRequestID(int value) {
    ctpapiJNI.CThostFtdcQuoteField_RequestID_set(swigCPtr, this, value);
  }

  public int getRequestID() {
    return ctpapiJNI.CThostFtdcQuoteField_RequestID_get(swigCPtr, this);
  }

  public void setBusinessUnit(String value) {
    ctpapiJNI.CThostFtdcQuoteField_BusinessUnit_set(swigCPtr, this, value);
  }

  public String getBusinessUnit() {
    return ctpapiJNI.CThostFtdcQuoteField_BusinessUnit_get(swigCPtr, this);
  }

  public void setAskOffsetFlag(char value) {
    ctpapiJNI.CThostFtdcQuoteField_AskOffsetFlag_set(swigCPtr, this, value);
  }

  public char getAskOffsetFlag() {
    return ctpapiJNI.CThostFtdcQuoteField_AskOffsetFlag_get(swigCPtr, this);
  }

  public void setBidOffsetFlag(char value) {
    ctpapiJNI.CThostFtdcQuoteField_BidOffsetFlag_set(swigCPtr, this, value);
  }

  public char getBidOffsetFlag() {
    return ctpapiJNI.CThostFtdcQuoteField_BidOffsetFlag_get(swigCPtr, this);
  }

  public void setAskHedgeFlag(char value) {
    ctpapiJNI.CThostFtdcQuoteField_AskHedgeFlag_set(swigCPtr, this, value);
  }

  public char getAskHedgeFlag() {
    return ctpapiJNI.CThostFtdcQuoteField_AskHedgeFlag_get(swigCPtr, this);
  }

  public void setBidHedgeFlag(char value) {
    ctpapiJNI.CThostFtdcQuoteField_BidHedgeFlag_set(swigCPtr, this, value);
  }

  public char getBidHedgeFlag() {
    return ctpapiJNI.CThostFtdcQuoteField_BidHedgeFlag_get(swigCPtr, this);
  }

  public void setQuoteLocalID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_QuoteLocalID_set(swigCPtr, this, value);
  }

  public String getQuoteLocalID() {
    return ctpapiJNI.CThostFtdcQuoteField_QuoteLocalID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcQuoteField_ExchangeID_get(swigCPtr, this);
  }

  public void setParticipantID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ParticipantID_set(swigCPtr, this, value);
  }

  public String getParticipantID() {
    return ctpapiJNI.CThostFtdcQuoteField_ParticipantID_get(swigCPtr, this);
  }

  public void setClientID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ClientID_set(swigCPtr, this, value);
  }

  public String getClientID() {
    return ctpapiJNI.CThostFtdcQuoteField_ClientID_get(swigCPtr, this);
  }

  public void setExchangeInstID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ExchangeInstID_set(swigCPtr, this, value);
  }

  public String getExchangeInstID() {
    return ctpapiJNI.CThostFtdcQuoteField_ExchangeInstID_get(swigCPtr, this);
  }

  public void setTraderID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_TraderID_set(swigCPtr, this, value);
  }

  public String getTraderID() {
    return ctpapiJNI.CThostFtdcQuoteField_TraderID_get(swigCPtr, this);
  }

  public void setInstallID(int value) {
    ctpapiJNI.CThostFtdcQuoteField_InstallID_set(swigCPtr, this, value);
  }

  public int getInstallID() {
    return ctpapiJNI.CThostFtdcQuoteField_InstallID_get(swigCPtr, this);
  }

  public void setNotifySequence(int value) {
    ctpapiJNI.CThostFtdcQuoteField_NotifySequence_set(swigCPtr, this, value);
  }

  public int getNotifySequence() {
    return ctpapiJNI.CThostFtdcQuoteField_NotifySequence_get(swigCPtr, this);
  }

  public void setOrderSubmitStatus(char value) {
    ctpapiJNI.CThostFtdcQuoteField_OrderSubmitStatus_set(swigCPtr, this, value);
  }

  public char getOrderSubmitStatus() {
    return ctpapiJNI.CThostFtdcQuoteField_OrderSubmitStatus_get(swigCPtr, this);
  }

  public void setTradingDay(String value) {
    ctpapiJNI.CThostFtdcQuoteField_TradingDay_set(swigCPtr, this, value);
  }

  public String getTradingDay() {
    return ctpapiJNI.CThostFtdcQuoteField_TradingDay_get(swigCPtr, this);
  }

  public void setSettlementID(int value) {
    ctpapiJNI.CThostFtdcQuoteField_SettlementID_set(swigCPtr, this, value);
  }

  public int getSettlementID() {
    return ctpapiJNI.CThostFtdcQuoteField_SettlementID_get(swigCPtr, this);
  }

  public void setQuoteSysID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_QuoteSysID_set(swigCPtr, this, value);
  }

  public String getQuoteSysID() {
    return ctpapiJNI.CThostFtdcQuoteField_QuoteSysID_get(swigCPtr, this);
  }

  public void setInsertDate(String value) {
    ctpapiJNI.CThostFtdcQuoteField_InsertDate_set(swigCPtr, this, value);
  }

  public String getInsertDate() {
    return ctpapiJNI.CThostFtdcQuoteField_InsertDate_get(swigCPtr, this);
  }

  public void setInsertTime(String value) {
    ctpapiJNI.CThostFtdcQuoteField_InsertTime_set(swigCPtr, this, value);
  }

  public String getInsertTime() {
    return ctpapiJNI.CThostFtdcQuoteField_InsertTime_get(swigCPtr, this);
  }

  public void setCancelTime(String value) {
    ctpapiJNI.CThostFtdcQuoteField_CancelTime_set(swigCPtr, this, value);
  }

  public String getCancelTime() {
    return ctpapiJNI.CThostFtdcQuoteField_CancelTime_get(swigCPtr, this);
  }

  public void setQuoteStatus(char value) {
    ctpapiJNI.CThostFtdcQuoteField_QuoteStatus_set(swigCPtr, this, value);
  }

  public char getQuoteStatus() {
    return ctpapiJNI.CThostFtdcQuoteField_QuoteStatus_get(swigCPtr, this);
  }

  public void setClearingPartID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ClearingPartID_set(swigCPtr, this, value);
  }

  public String getClearingPartID() {
    return ctpapiJNI.CThostFtdcQuoteField_ClearingPartID_get(swigCPtr, this);
  }

  public void setSequenceNo(int value) {
    ctpapiJNI.CThostFtdcQuoteField_SequenceNo_set(swigCPtr, this, value);
  }

  public int getSequenceNo() {
    return ctpapiJNI.CThostFtdcQuoteField_SequenceNo_get(swigCPtr, this);
  }

  public void setAskOrderSysID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_AskOrderSysID_set(swigCPtr, this, value);
  }

  public String getAskOrderSysID() {
    return ctpapiJNI.CThostFtdcQuoteField_AskOrderSysID_get(swigCPtr, this);
  }

  public void setBidOrderSysID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_BidOrderSysID_set(swigCPtr, this, value);
  }

  public String getBidOrderSysID() {
    return ctpapiJNI.CThostFtdcQuoteField_BidOrderSysID_get(swigCPtr, this);
  }

  public void setFrontID(int value) {
    ctpapiJNI.CThostFtdcQuoteField_FrontID_set(swigCPtr, this, value);
  }

  public int getFrontID() {
    return ctpapiJNI.CThostFtdcQuoteField_FrontID_get(swigCPtr, this);
  }

  public void setSessionID(int value) {
    ctpapiJNI.CThostFtdcQuoteField_SessionID_set(swigCPtr, this, value);
  }

  public int getSessionID() {
    return ctpapiJNI.CThostFtdcQuoteField_SessionID_get(swigCPtr, this);
  }

  public void setUserProductInfo(String value) {
    ctpapiJNI.CThostFtdcQuoteField_UserProductInfo_set(swigCPtr, this, value);
  }

  public String getUserProductInfo() {
    return ctpapiJNI.CThostFtdcQuoteField_UserProductInfo_get(swigCPtr, this);
  }

  public void setStatusMsg(String value) {
    ctpapiJNI.CThostFtdcQuoteField_StatusMsg_set(swigCPtr, this, value);
  }

  public String getStatusMsg() {
    return ctpapiJNI.CThostFtdcQuoteField_StatusMsg_get(swigCPtr, this);
  }

  public void setActiveUserID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ActiveUserID_set(swigCPtr, this, value);
  }

  public String getActiveUserID() {
    return ctpapiJNI.CThostFtdcQuoteField_ActiveUserID_get(swigCPtr, this);
  }

  public void setBrokerQuoteSeq(int value) {
    ctpapiJNI.CThostFtdcQuoteField_BrokerQuoteSeq_set(swigCPtr, this, value);
  }

  public int getBrokerQuoteSeq() {
    return ctpapiJNI.CThostFtdcQuoteField_BrokerQuoteSeq_get(swigCPtr, this);
  }

  public void setAskOrderRef(String value) {
    ctpapiJNI.CThostFtdcQuoteField_AskOrderRef_set(swigCPtr, this, value);
  }

  public String getAskOrderRef() {
    return ctpapiJNI.CThostFtdcQuoteField_AskOrderRef_get(swigCPtr, this);
  }

  public void setBidOrderRef(String value) {
    ctpapiJNI.CThostFtdcQuoteField_BidOrderRef_set(swigCPtr, this, value);
  }

  public String getBidOrderRef() {
    return ctpapiJNI.CThostFtdcQuoteField_BidOrderRef_get(swigCPtr, this);
  }

  public void setForQuoteSysID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_ForQuoteSysID_set(swigCPtr, this, value);
  }

  public String getForQuoteSysID() {
    return ctpapiJNI.CThostFtdcQuoteField_ForQuoteSysID_get(swigCPtr, this);
  }

  public void setBranchID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_BranchID_set(swigCPtr, this, value);
  }

  public String getBranchID() {
    return ctpapiJNI.CThostFtdcQuoteField_BranchID_get(swigCPtr, this);
  }

  public void setInvestUnitID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_InvestUnitID_set(swigCPtr, this, value);
  }

  public String getInvestUnitID() {
    return ctpapiJNI.CThostFtdcQuoteField_InvestUnitID_get(swigCPtr, this);
  }

  public void setAccountID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_AccountID_set(swigCPtr, this, value);
  }

  public String getAccountID() {
    return ctpapiJNI.CThostFtdcQuoteField_AccountID_get(swigCPtr, this);
  }

  public void setCurrencyID(String value) {
    ctpapiJNI.CThostFtdcQuoteField_CurrencyID_set(swigCPtr, this, value);
  }

  public String getCurrencyID() {
    return ctpapiJNI.CThostFtdcQuoteField_CurrencyID_get(swigCPtr, this);
  }

  public void setIPAddress(String value) {
    ctpapiJNI.CThostFtdcQuoteField_IPAddress_set(swigCPtr, this, value);
  }

  public String getIPAddress() {
    return ctpapiJNI.CThostFtdcQuoteField_IPAddress_get(swigCPtr, this);
  }

  public void setMacAddress(String value) {
    ctpapiJNI.CThostFtdcQuoteField_MacAddress_set(swigCPtr, this, value);
  }

  public String getMacAddress() {
    return ctpapiJNI.CThostFtdcQuoteField_MacAddress_get(swigCPtr, this);
  }

  public CThostFtdcQuoteField() {
    this(ctpapiJNI.new_CThostFtdcQuoteField(), true);
  }

}
