/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcBrokerLimitPosiParamField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcBrokerLimitPosiParamField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcBrokerLimitPosiParamField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcBrokerLimitPosiParamField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_BrokerID_get(swigCPtr, this);
  }

  public void setInstrumentID(String value) {
    ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_ExchangeID_get(swigCPtr, this);
  }

  public void setTotalVolume(double value) {
    ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_TotalVolume_set(swigCPtr, this, value);
  }

  public double getTotalVolume() {
    return ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_TotalVolume_get(swigCPtr, this);
  }

  public void setLongVolume(double value) {
    ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_LongVolume_set(swigCPtr, this, value);
  }

  public double getLongVolume() {
    return ctpapiJNI.CThostFtdcBrokerLimitPosiParamField_LongVolume_get(swigCPtr, this);
  }

  public CThostFtdcBrokerLimitPosiParamField() {
    this(ctpapiJNI.new_CThostFtdcBrokerLimitPosiParamField(), true);
  }

}
