/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcLinkManField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcLinkManField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcLinkManField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcLinkManField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcLinkManField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcLinkManField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiJNI.CThostFtdcLinkManField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiJNI.CThostFtdcLinkManField_InvestorID_get(swigCPtr, this);
  }

  public void setPersonType(char value) {
    ctpapiJNI.CThostFtdcLinkManField_PersonType_set(swigCPtr, this, value);
  }

  public char getPersonType() {
    return ctpapiJNI.CThostFtdcLinkManField_PersonType_get(swigCPtr, this);
  }

  public void setIdentifiedCardType(char value) {
    ctpapiJNI.CThostFtdcLinkManField_IdentifiedCardType_set(swigCPtr, this, value);
  }

  public char getIdentifiedCardType() {
    return ctpapiJNI.CThostFtdcLinkManField_IdentifiedCardType_get(swigCPtr, this);
  }

  public void setIdentifiedCardNo(String value) {
    ctpapiJNI.CThostFtdcLinkManField_IdentifiedCardNo_set(swigCPtr, this, value);
  }

  public String getIdentifiedCardNo() {
    return ctpapiJNI.CThostFtdcLinkManField_IdentifiedCardNo_get(swigCPtr, this);
  }

  public void setPersonName(String value) {
    ctpapiJNI.CThostFtdcLinkManField_PersonName_set(swigCPtr, this, value);
  }

  public String getPersonName() {
    return ctpapiJNI.CThostFtdcLinkManField_PersonName_get(swigCPtr, this);
  }

  public void setTelephone(String value) {
    ctpapiJNI.CThostFtdcLinkManField_Telephone_set(swigCPtr, this, value);
  }

  public String getTelephone() {
    return ctpapiJNI.CThostFtdcLinkManField_Telephone_get(swigCPtr, this);
  }

  public void setAddress(String value) {
    ctpapiJNI.CThostFtdcLinkManField_Address_set(swigCPtr, this, value);
  }

  public String getAddress() {
    return ctpapiJNI.CThostFtdcLinkManField_Address_get(swigCPtr, this);
  }

  public void setZipCode(String value) {
    ctpapiJNI.CThostFtdcLinkManField_ZipCode_set(swigCPtr, this, value);
  }

  public String getZipCode() {
    return ctpapiJNI.CThostFtdcLinkManField_ZipCode_get(swigCPtr, this);
  }

  public void setPriority(int value) {
    ctpapiJNI.CThostFtdcLinkManField_Priority_set(swigCPtr, this, value);
  }

  public int getPriority() {
    return ctpapiJNI.CThostFtdcLinkManField_Priority_get(swigCPtr, this);
  }

  public void setUOAZipCode(String value) {
    ctpapiJNI.CThostFtdcLinkManField_UOAZipCode_set(swigCPtr, this, value);
  }

  public String getUOAZipCode() {
    return ctpapiJNI.CThostFtdcLinkManField_UOAZipCode_get(swigCPtr, this);
  }

  public void setPersonFullName(String value) {
    ctpapiJNI.CThostFtdcLinkManField_PersonFullName_set(swigCPtr, this, value);
  }

  public String getPersonFullName() {
    return ctpapiJNI.CThostFtdcLinkManField_PersonFullName_get(swigCPtr, this);
  }

  public CThostFtdcLinkManField() {
    this(ctpapiJNI.new_CThostFtdcLinkManField(), true);
  }

}
