/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcBrokerUserRightAssignField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcBrokerUserRightAssignField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcBrokerUserRightAssignField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpJNI.delete_CThostFtdcBrokerUserRightAssignField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBrokerID(String value) {
    ctpJNI.CThostFtdcBrokerUserRightAssignField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpJNI.CThostFtdcBrokerUserRightAssignField_BrokerID_get(swigCPtr, this);
  }

  public void setDRIdentityID(int value) {
    ctpJNI.CThostFtdcBrokerUserRightAssignField_DRIdentityID_set(swigCPtr, this, value);
  }

  public int getDRIdentityID() {
    return ctpJNI.CThostFtdcBrokerUserRightAssignField_DRIdentityID_get(swigCPtr, this);
  }

  public void setTradeable(int value) {
    ctpJNI.CThostFtdcBrokerUserRightAssignField_Tradeable_set(swigCPtr, this, value);
  }

  public int getTradeable() {
    return ctpJNI.CThostFtdcBrokerUserRightAssignField_Tradeable_get(swigCPtr, this);
  }

  public CThostFtdcBrokerUserRightAssignField() {
    this(ctpJNI.new_CThostFtdcBrokerUserRightAssignField(), true);
  }

}
