/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.ctp;

public class CThostFtdcExecFreezeField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CThostFtdcExecFreezeField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CThostFtdcExecFreezeField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ctpapiJNI.delete_CThostFtdcExecFreezeField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInstrumentID(String value) {
    ctpapiJNI.CThostFtdcExecFreezeField_InstrumentID_set(swigCPtr, this, value);
  }

  public String getInstrumentID() {
    return ctpapiJNI.CThostFtdcExecFreezeField_InstrumentID_get(swigCPtr, this);
  }

  public void setExchangeID(String value) {
    ctpapiJNI.CThostFtdcExecFreezeField_ExchangeID_set(swigCPtr, this, value);
  }

  public String getExchangeID() {
    return ctpapiJNI.CThostFtdcExecFreezeField_ExchangeID_get(swigCPtr, this);
  }

  public void setBrokerID(String value) {
    ctpapiJNI.CThostFtdcExecFreezeField_BrokerID_set(swigCPtr, this, value);
  }

  public String getBrokerID() {
    return ctpapiJNI.CThostFtdcExecFreezeField_BrokerID_get(swigCPtr, this);
  }

  public void setInvestorID(String value) {
    ctpapiJNI.CThostFtdcExecFreezeField_InvestorID_set(swigCPtr, this, value);
  }

  public String getInvestorID() {
    return ctpapiJNI.CThostFtdcExecFreezeField_InvestorID_get(swigCPtr, this);
  }

  public void setPosiDirection(char value) {
    ctpapiJNI.CThostFtdcExecFreezeField_PosiDirection_set(swigCPtr, this, value);
  }

  public char getPosiDirection() {
    return ctpapiJNI.CThostFtdcExecFreezeField_PosiDirection_get(swigCPtr, this);
  }

  public void setOptionsType(char value) {
    ctpapiJNI.CThostFtdcExecFreezeField_OptionsType_set(swigCPtr, this, value);
  }

  public char getOptionsType() {
    return ctpapiJNI.CThostFtdcExecFreezeField_OptionsType_get(swigCPtr, this);
  }

  public void setVolume(int value) {
    ctpapiJNI.CThostFtdcExecFreezeField_Volume_set(swigCPtr, this, value);
  }

  public int getVolume() {
    return ctpapiJNI.CThostFtdcExecFreezeField_Volume_get(swigCPtr, this);
  }

  public void setFrozenAmount(double value) {
    ctpapiJNI.CThostFtdcExecFreezeField_FrozenAmount_set(swigCPtr, this, value);
  }

  public double getFrozenAmount() {
    return ctpapiJNI.CThostFtdcExecFreezeField_FrozenAmount_get(swigCPtr, this);
  }

  public CThostFtdcExecFreezeField() {
    this(ctpapiJNI.new_CThostFtdcExecFreezeField(), true);
  }

}
